### ISSUE TITLE
MRI to CT model 

### ISSUE THREAD

**Issue by plbenveniste** [neuropoly/totalspineseg#17]
The goal of this model is to accurately transform mri scans into ct scans. The greater objective is to be able to use Total Segmentator, which was trained on CT scans, on MRI images in order to perform segmentation.

To do:
- [x] Literature review (maybe look at [this GH](https://github.com/QingLyu0828/diffusion_mri_to_ct_conversion))
- [x] Data pre-processing (MRI and CT data are contained in same volume so not much to do in terms of pre-processing)
- [ ] Modify script for training and testing of the model
- [ ] Train and test a model
- [ ] Result analysis

**Comment by yw7** [comment]
I'm closing this issue because we ended up using different methos (registration to PAM50)
