### ISSUE TITLE
Adding sacrum to totalsegmentator

### ISSUE THREAD

**Issue by NathanMolinier** [neuropoly/totalspineseg#18]
## Description

To improve the range of the totalspineseg model, we decided to add the sacrum as a new structure of the spine. However, because creating these masks from scratch may take too long, we decided to train a new nnunet model using 3 open-source datasets (GoldAtlas, SynthRAD2023 and MRSpineSeg):

| [GoldAtlas](https://zenodo.org/records/583096) | [SynthRAD2023](https://synthrad2023.grand-challenge.org/) | [MRSpineSeg](https://paperswithcode.com/dataset/mrspineseg-challenge) |
| :---: | :---: | :---: |
| <img width="780" alt="Screenshot 2024-01-02 at 5 10 39 AM" src="https://github.com/neuropoly/totalsegmentator-mri/assets/68945192/a324ba05-1118-4eb3-bd4f-f9aabd077477">  | <img width="628" alt="Screenshot 2024-01-02 at 5 10 53 AM" src="https://github.com/neuropoly/totalsegmentator-mri/assets/68945192/10ddd780-ec42-4540-a091-19d2b2dc3e53"> | <img width="671" alt="Screenshot 2024-01-02 at 5 11 19 AM" src="https://github.com/neuropoly/totalsegmentator-mri/assets/68945192/a0069483-ad59-48bd-9c3e-a436888a39d7"> |

However, even if T1w and T2w contrasts are available in addition to the CT images most of the masks were only created for CT images.

Using these same masks for T1w and T2w images is possible but will lead to small misalignments. Also, because T1w, T2w and CT images may have different shapes and resolutions, the scanner coordinates should be used.

![Kapture 2024-01-02 at 05 30 10](https://github.com/neuropoly/totalsegmentator-mri/assets/68945192/cabb159d-26fc-409a-832e-6abbd5a790a2)

## Generation of the sacrum segmentations

Goldatlas: 
- Generation of the sacrum segmentations on the CT images of each patient using the CT [totalsegmentator](https://github.com/wasserth/TotalSegmentator)
- Registration of the CT segmentation to the T1w space and T2w space using the [spinalcordtoolbox](https://github.com/spinalcordtoolbox/spinalcordtoolbox)

SynthRAD2023: 
- Generation of the sacrum segmentations on the CT images of each patient using the CT [totalsegmentator](https://github.com/wasserth/TotalSegmentator)
- Registration of the CT segmentation to the T1w space using the [spinalcordtoolbox](https://github.com/spinalcordtoolbox/spinalcordtoolbox)

MRSpineSeg:
- T2w segmentations of the spine were already available in the dataset.

**Comment by yw7** [comment]
@NathanMolinier can we close this?
