### ISSUE TITLE
Change labels to handle extra/missing cervical, thoracic and lumbar vertebrae

### ISSUE THREAD

**Issue by yw7** [neuropoly/totalspineseg#38]
Make the output labels continue for each region of the spine (cervical, thoracic and lumbar) in order to support anomalies in number of vertebra (13 thoracic vertebra for example).
For example: 101-120 for Cervical 121-140 for thoracic, 141-160 for lumbar.
To do so we do not need to retrain the model,just change the labels map for input and output and also the vertebrae labeling algorithm.

**Comment by yw7** [comment]
![image](https://github.com/user-attachments/assets/535df38e-0a63-4cde-852b-ea68338e9099)

**Comment by NathanMolinier** [comment]
Based on this, we should rethink our labeling strategy. It looks really important to me ! Changing the output labels is also a good thing to make the usage clearer for new users.

**Comment by NathanMolinier** [comment]
Is it possible to slightly shift the labels by 1 for the vertebrae ? 

To have:
- C1 --> 11
- C2 --> 12
- T1 --> 21
- L5 --> 45 

It might be more intuitive for people ?
