### ISSUE TITLE
Pretrained weights for segmentation? 

### ISSUE THREAD

**Issue by Amritpal-001** [neuropoly/totalspineseg#39]
Thanks for the amazing work. I want to use this model in my research pipeline.
Are the pre-trained weights available?

**Comment by yw7** [comment]
Hi @Amritpal-001,

Thank you for your interest in our work!

We have a pre-release version of the model available here: https://github.com/neuropoly/totalspineseg/releases/tag/r20240628 , which works on canonical reoriented images. However, I recommend checking back in about two weeks for the final version of the model, which will be included in a new release.

Best,
Yehuda

**Comment by yw7** [comment]
Hi @Amritpal-001 , you can try https://github.com/neuropoly/totalspineseg/releases/tag/r20240819 .
