### ISSUE TITLE
make the files public on google drive

### ISSUE THREAD

**Issue by BarhateManthan** [neuropoly/totalspineseg#41]
there are 3 zip folders that are to be downloaded from the g-drive.
users everytime need to ask access.
please make the folders public and update the link.

**Comment by jcohenadad** [comment]
Hi,

Some data are public (in which case they will be put on OpenNeuro instead of gdrive) and some are not (in which case, they are _de facto_ stored in our internal server).

Related to https://github.com/neuropoly/totalspineseg/issues/35 https://github.com/neuropoly/totalspineseg/issues/14
