### ISSUE TITLE
Trained Model weights

### ISSUE THREAD

**Issue by hopkin22** [neuropoly/totalspineseg#47]
It appears much of your training data is private. Do you by chance have the available pytorch final trained model weights for implementation? Otherwise is it possible to get access to your private training dataset for self training? Sincerely appreciate your contribution!

**Comment by jcohenadad** [comment]
> Do you by chance have the available pytorch final trained model weights for implementation? 

Yes, models are shared via each release. @yw7 can assist

> Otherwise is it possible to get access to your private training dataset for self training? Sincerely appreciate your contribution!

Some are private (and cannot be shared), but most of the data is public (eg: SPIDER, spine-generic)

**Comment by yw7** [comment]
> It appears much of your training data is private. Do you by chance have the available pytorch final trained model weights for implementation? Otherwise is it possible to get access to your private training dataset for self training? Sincerely appreciate your contribution!

Last pertained weights available here: https://github.com/neuropoly/totalspineseg/releases/tag/r20240826

But you can follow the instructions for [installation](https://github.com/neuropoly/totalspineseg?tab=readme-ov-file#installation) and [inference](https://github.com/neuropoly/totalspineseg?tab=readme-ov-file#inference) in the readme, if you run inference it will automatically download last released weights and use them.
