### ISSUE TITLE
Publish on ZENODO and add badge

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/totalspineseg#49]
and add ISMRM citation (for now)

**Comment by yw7** [comment]
> and add ISMRM citation (for now)

This is in the main RADME, is it OK for now? How can we add to zenodo?

https://github.com/neuropoly/totalspineseg/blob/d3318be8c84bb10ce494d2fb3b1cf7e52c86b4b7/README.md?plain=1#L5-L6

**Comment by jcohenadad** [comment]
> How can we add to zenodo?

https://help.zenodo.org/docs/deposit/create-new-upload/

**Comment by yw7** [comment]
> > How can we add to zenodo?
> 
> https://help.zenodo.org/docs/deposit/create-new-upload/

OK! Thnks!!
I meant,  should I use my own account? Or Neuropoly? Auto Link to the GH release?

**Comment by jcohenadad** [comment]
your account and add us as editors
