### ISSUE TITLE
Issue with resampling

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/totalspineseg#51]
Version: https://github.com/neuropoly/totalspineseg/commit/d3318be8c84bb10ce494d2fb3b1cf7e52c86b4b7

When dealing with an SCT user, I realized that the resampling done by TotalSpineSeg changes the physical dimensions of the image in an unrealistic way.

[Original image](https://www.dropbox.com/scl/fi/y7c22cvwhdox043ay51n9/HD5_20240404_013732IMG00021t2tsesags002a001_5.nii.gz?rlkey=obff91acpqlw7m5kyhi87ptn5&dl=0):

![image](https://github.com/user-attachments/assets/53dace6f-32ad-48d1-8984-0bf05973c451)

[Resampled image](https://www.dropbox.com/s/6gvajphrt5unpx6/HD5_20240404_013732IMG00021t2tsesags002a001_5_0000.nii.gz?dl=0) (located under `<OUTPUT>/input`):

![image](https://github.com/user-attachments/assets/d6ab888c-df89-441e-aa1f-7d2d1991e0d2)

**Comment by yw7** [comment]
As written in https://github.com/neuropoly/totalspineseg/issues/53:
I think the error is from a mismatch between the sform and qform:

![image](https://github.com/user-attachments/assets/fd1dac9d-b5dd-485a-b31b-4668b113f9a4)


After fixing this mismatch with the command: `sct_image -i HD5_20240404_013732IMG00021t2tsesags002a001_5.nii.gz -set-sform-to-qform -o  HD5_20240404_013732IMG00021t2tsesags002a001_5_fixed.nii.gz` I can run the image without error:

![image](https://github.com/user-attachments/assets/d943c01d-56e5-4e7e-a278-8e8c23b871fa)

**Comment by NathanMolinier** [comment]
Close as solved
