### ISSUE TITLE
Long inference time

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/totalspineseg#52]
It took about 8h to process 2 images (see example of one image in #51) on my macbook with Intel CPU (12 cores). Is this normal?

**Comment by yw7** [comment]
I think yes. without GPU inference time can be very long since the network is 3D and use multi-calss (10 for step 1 and 18 for step 2). In next version we using smaller network so hopefully it will be a little bit better.
https://github.com/neuropoly/totalspineseg/pull/42
