### ISSUE TITLE
Input single file instead of directory

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/totalspineseg#60]
Most users expect to input a single NIfTI file, instead of a directory. Moreover, anticipating the merge with SCT where single files are processed, can we consider having a CLI that asks for an input file instead of (or in addition to) an input folder?

**Comment by yw7** [comment]
Apologies for the delayed response, and thank you so much for the suggestion.
This feature is now implemented, and the README has been updated accordingly in this commit https://github.com/neuropoly/totalspineseg/pull/46/commits/74020ef2ad53a23d8e5dad43944648200d9c463b.
This will be merged with https://github.com/neuropoly/totalspineseg/pull/46.
