### ISSUE TITLE
Inconsistent release naming strategy

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/totalspineseg#72]
As we are now putting the releases on Zenodo, the naming of the releases should be consistent. Currently, it is not:

![image](https://github.com/user-attachments/assets/ba525643-1b44-4b8c-b6e1-d0e74cefd237)

I suggest we stick with "TotalSpineSeg-rYYYYMMDD".

And in the changelog, we describe what was done (automatic changlog from the PRs, and add text manually if necessary)

**Comment by yw7** [comment]
We will follow "TotalSpineSeg-rYYYYMMDD" for next release.
Regarding Sacrum segmentation, it was a pre release with the sacrum model and should not be in the zenodo.
it is possible if necessary, to ask to delete the associated zenodo release (https://zenodo.org/records/13891845) within 30 days here: https://zenodo.org/support.

**Comment by yw7** [comment]
I'm closing this issue. We will follow 'TotalSpineSeg-rYYYYMMDD' from now on.
